### Set BDE_parameters
CROSSVAL <- 5
OFFSET <- 0.1
NBASEFEAT <- 390
CFSBEST <- 100 #isNotUsed
NP <- 20
GENERATION <- 15
MUTFACTOR <- 0.3
CR <- 0.5
SEEDRNG <- 12
LMD_CENT <- 1
#NUMCORES <- detectCores() #isNotUsed
#
BDE_Parameters <- c(CROSSVAL, OFFSET, NBASEFEAT, CFSBEST, NP, GENERATION, MUTFACTOR, CR, SEEDRNG)
names(BDE_Parameters) <- c('CROSSVAL', 'OFFSET', 'NBASEFEAT', 'CFSBEST', 'NP', 'GENERATION', 'MUTFACTOR', 'CR', 'SEEDRNG')